### ISSUE TITLE
NoSuchBucket

### ISSUE THREAD

**Issue by sollyucko** [AndrewDryga/vagrant-box-osx#79] opened 2020-06-05 04:07 UTC
None of the links provided seem to work.

**Comment by Tobjoern** [comment] 2020-08-15 07:58
+1, seems like they were removed

**Comment by useretail** [comment] 2020-08-23 17:13
can someone re-upload old ones?

**Comment by AndrewDryga** [comment] 2021-01-19 20:13
Duplicate of #81

**Closed by AndrewDryga** 2021-01-19 20:13 UTC
